# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master  # Change this to your default branch if different

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify the Node.js version you want to use
          cache: 'pnpm'  # Cache pnpm dependencies

      - name: Install pnpm
        run: npm install -g pnpm  # Install pnpm globally

      - name: Install dependencies
        run: pnpm install  # Use pnpm to install dependencies

      - name: Build
        run: pnpm run build  # Build the Next.js application

      - name: Export
        run: pnpm run export  # Export the Next.js application

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Adjust this path if your export directory is different
